In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
climatechange=pd.read_csv('GlobalLandTemperaturesByState.csv')

In [54]:
climatechange.head()

           dt  AverageTemperature  AverageTemperatureUncertainty State Country
0  1855-05-01              25.544                          1.171  Acre  Brazil
1  1855-06-01              24.228                          1.103  Acre  Brazil
2  1855-07-01              24.371                          1.044  Acre  Brazil
3  1855-08-01              25.427                          1.073  Acre  Brazil
4  1855-09-01              25.675                          1.014  Acre  Brazil

In [55]:
climatechange.isnull().sum()

dt                                   0
AverageTemperature               25648
AverageTemperatureUncertainty    25648
State                                0
Country                              0
dtype: int64

In [56]:
climatechange['year'] = pd.DatetimeIndex(climatechange['dt']).year
climatechange['month'] = pd.DatetimeIndex(climatechange['dt']).month
climatechange['dt']=pd.to_datetime(climatechange.dt)
climatechange=climatechange[climatechange['year']>1980]
climatechange.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,State,Country,year,month
1508,1981-01-01,26.076,0.237,Acre,Brazil,1981,1
1509,1981-02-01,25.635,0.383,Acre,Brazil,1981,2
1510,1981-03-01,26.244,0.348,Acre,Brazil,1981,3
1511,1981-04-01,26.038,0.211,Acre,Brazil,1981,4
1512,1981-05-01,26.463,0.353,Acre,Brazil,1981,5

In [57]:
des=climatechange.describe()
des.year=des.year.astype(int)
des.month=des.month.astype(int)

In [58]:
des

       AverageTemperature  AverageTemperatureUncertainty   year  month
count        94532.000000                   94532.000000  94713  94713
mean            10.351600                       0.299140   1996      6
std             13.701776                       0.163417      9      3
min            -43.002000                       0.044000   1981      1
25%              1.139750                       0.204000   1989      3
50%             12.665000                       0.263000   1997      6
75%             21.358000                       0.346000   2005      9
max             36.339000                       5.435000   2013     12

In [59]:
climatechange.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,State,Country,year,month
1508,1981-01-01,26.076,0.237,Acre,Brazil,1981,1
1509,1981-02-01,25.635,0.383,Acre,Brazil,1981,2
1510,1981-03-01,26.244,0.348,Acre,Brazil,1981,3
1511,1981-04-01,26.038,0.211,Acre,Brazil,1981,4
1512,1981-05-01,26.463,0.353,Acre,Brazil,1981,5

In [60]:
climatechange.isnull().sum()

dt                                 0
AverageTemperature               181
AverageTemperatureUncertainty    181
State                              0
Country                            0
year                               0
month                              0
dtype: int64

In [61]:
pip install pycountry-convert

Requirement already satisfied: pycountry-convert in ./Datasets/anaconda3/lib/python3.8/site-packages (0.7.2)
Requirement already satisfied: wheel>=0.30.0 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (0.35.1)
Requirement already satisfied: pytest>=3.4.0 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (6.2.2)
Requirement already satisfied: pycountry>=16.11.27.1 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (20.7.3)
Requirement already satisfied: pytest-cov>=2.5.1 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (2.11.1)
Requirement already satisfied: pprintpp>=0.3.0 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (0.4.0)
Requirement already satisfied: repoze.lru>=0.7 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (0.7)
Requirement already satisfied: pytest-mock>=1.6.3 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pycountry-convert) (3.5.1)
Requirement already satisfied: packaging in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest>=3.4.0->pycountry-convert) (20.4)
Requirement already satisfied: py>=1.8.2 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest>=3.4.0->pycountry-convert) (1.9.0)
Requirement already satisfied: iniconfig in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: toml in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest>=3.4.0->pycountry-convert) (0.10.1)
Requirement already satisfied: attrs>=19.2.0 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest>=3.4.0->pycountry-convert) (20.3.0)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest>=3.4.0->pycountry-convert) (0.13.1)
Requirement already satisfied: coverage>=5.2.1 in ./Datasets/anaconda3/lib/python3.8/site-packages (from pytest-cov>=2.5.1->pycountry-convert) (5.4)
Requirement already satisfied: six in ./Datasets/anaconda3/lib/python3.8/site-packages (from packaging->pytest>=3.4.0->pycountry-convert) (1.15.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./Datasets/anaconda3/lib/python3.8/site-packages (from packaging->pytest>=3.4.0->pycountry-convert) (2.4.7)
Note: you may need to restart the kernel to use updated packages.

In [62]:
from pycountry_convert import country_alpha2_to_continent_code, country_name_to_country_alpha2

In [63]:
import pycountry_convert as pc

In [64]:
def country_to_continent(country_name):
    country_alpha2 = pc.country_name_to_country_alpha2(country_name)
    country_continent_code = pc.country_alpha2_to_continent_code(country_alpha2)
    country_continent_name = pc.convert_continent_code_to_continent_name(country_continent_code)
    return country_continent_name
countries = list(climatechange['Country'])

[country_to_continent(Country)for Country in countries]

['South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'South America',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 'Europe',
 ...]

In [71]:
climatechange['continent'] = climatechange['Country'].apply(country_to_continent)

In [72]:
climatechange.to_csv('Global_Land_Temp.csv', sep=',')